### ISSUE TITLE
Login failed from frontend with "CSRF token not found in request"

### ISSUE THREAD

**Issue by k2glyph** [Goxiaoy/go-saas-kit#6]
While trying to login:
![image](https://user-images.githubusercontent.com/8824209/155292316-f8026f76-3f67-4f36-9f07-b577d99b3462.png)

Config file
![image](https://user-images.githubusercontent.com/8824209/155292429-c72942e5-4edd-4c2d-ab20-cccf52dfd307.png)

**Comment by k2glyph** [comment]
@Goxiaoy can you please check this also?

**Comment by Goxiaoy** [comment]
Fixed.
Notice: this project is not production ready. use at your own risk
