### ISSUE TITLE
Do we need to keep all *.proto in git?

### ISSUE THREAD

**Issue by k2glyph** [Goxiaoy/go-saas-kit#7]
It's an auto-generated file right @Goxiaoy. Can we not put it in gitignore?

**Comment by Goxiaoy** [comment]
@k2glyph Yes, we need proto files in git
We use a microservice framework called [kratos](https://github.com/go-kratos/kratos) 
*.proto are [protobuf](https://developers.google.com/protocol-buffers) files developed by google
`make api` will use  
`google.golang.org/grpc/cmd/protoc-gen-go-grpc` to generate grpc server codes
`github.com/go-kratos/kratos/cmd/protoc-gen-go-http` to generate http server codes
